// src/components/Header.vue
<script setup lang="ts">
</script>

<template>
    <nav class='navbar navbar-expand-sm bg-light fixed-top' id='customNav'>
      <div class='container-fluid'>
        <ul class='navbar-nav justify-content-start'>
          <a href='https://github.com/pratikkabade'>
            <img alt='a' id='hrtLogo' src='https://avatars.githubusercontent.com/u/108847584?s=200&v=4' draggable='false' />
          </a>
        </ul>
        <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
          <i class='fa-solid fa-caret-down'></i>
        </button>
       
        <div class='collapse navbar-collapse justify-content-end' id='navbarSupportedContent'>
       
          <ul class='navbar-nav justify-content-end'>
            <li class='barItem'>
              <a class='nav-link' href='#'>One</a>
            </li>
            <li class='barItem'>
              <a class='nav-link' href='#'>Two</a>
            </li>
          </ul>
       
        </div>
      </div>
    </nav>
</template>

// src/components/Header.svelte
<nav class="navbar navbar-expand-sm bg-light fixed-top" id="customNav">
  <div class="container-fluid">
    <ul class="navbar-nav justify-content-start">
      <a href="https://github.com/pratikkabade">
        <img
          alt="a"
          id="hrtLogo"
          src="https://avatars.githubusercontent.com/u/108847584?s=200&v=4"
          draggable="false"
        />
      </a>
    </ul>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fa-solid fa-caret-down" />
    </button>

    <div
      class="collapse navbar-collapse justify-content-end"
      id="navbarSupportedContent"
    >
      <ul class="navbar-nav justify-content-end">
        <li class="barItem">
          <a class="nav-link" href="#">One</a>
        </li>
        <li class="barItem">
          <a class="nav-link" href="#">Two</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
